' 跨语言：调 C 共享库
NATIVE FUNCTION ui_scr_w() AS INTEGER
END FUNCTION
NATIVE SUB ui_rect(x AS INTEGER, y AS INTEGER, w AS INTEGER, h AS INTEGER, c AS INTEGER, f AS INTEGER, lw AS INTEGER, r AS INTEGER)
END SUB
ui_rect(10, 20, 30, 40, 255, 1, 2, 3)
PRINT "w="
PRINT ui_scr_w()
PRINT "\n"
