' DATA / READ / RESTORE（经典游戏的数据表）
DIM a AS INTEGER
DIM b AS INTEGER
DIM c AS INTEGER
READ a, b, c
PRINT "READ="; a; b; c
RESTORE
READ a
PRINT "RESTORE="; a
DATA 11, 22, 33
' EXPECT: READ=112233|RESTORE=11
