(define g 0)
(define (w1) (set! g 5))
(w1)
(print "A=") (print g)
(define (add2 a b) (+ a b))
(print "B=") (print (add2 3 4))
(define (len1 s) (strlen s))
(print "C=") (print (len1 "abcd"))
(define (multi x) (set! g x) (+ x 1))
(print "D=") (print (multi 9))
(define (nlp) (let loop ((i 0) (s 0)) (if (< i 5) (loop (+ i 1) (+ s i)) s)))
(print "E=") (print (nlp))
(define (many) (let ((a 1) (b 2) (c 3) (d 4) (e 5)) (+ a b c d e)))
(print "F=") (print (many))
