PackageIdentifier: Aleckstygit.WayCoder
PackageVersion: 0.96.4
InstallerLocale: zh-CN
InstallerType: portable
Commands:
  - waycoder
Installers:
  - Architecture: x64
    InstallerUrl: https://gitee.com/aleckstygit/way-coder/releases/download/v0.96.4/waycoder-v0.96.4-win-x64.zip
    InstallerSha256: 8a6e927d083503fa87251632b2cbb2580c3ccc858ec2384b9480c6440845970b
  - Architecture: arm64
    InstallerUrl: https://gitee.com/aleckstygit/way-coder/releases/download/v0.96.4/waycoder-v0.96.4-win-arm64.zip
    InstallerSha256: 3d297f33b0253d130df6e557af29292beaf77ab8259093b86fd164b26ed04530
ManifestType: installer
ManifestVersion: 1.6.0
